spring:
  data:
    mongodb:
      database: xh_hear
      host: 192.168.5.6
      port: 50000
      password: XHTec@2016
      username: xh_rw
      authentication-database: admin

  redis:
    host: 192.168.5.9 #服务器IP
    port: 19000 #端口
    timeout: 10000ms #超时时间
    jedis:
      pool:
        max-active: 200 #可用连接实例的最大数目
        max-idle: 200 #连接池最大空闲实例
        min-idle: 10 #连接池最小空闲实例
        max-wait: 5000ms #等待可用连接的最大时间(单位毫秒)
  cloud:
    bus:
      enabled: false
  sleuth:
    stream:
      enabled: false

  endpoints:
    enabled: true
    info:
      sensitive: false
    health:
      sensitive: false

hystrix:
  threadpool:
    default:
      maximumSize: 200
      coreSize: 500
      maxQueueSize: 3000
      keepAliveTimeMinutes: 10
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 2000
          thread:
            timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      base-path: /mgm
      exposure:
        include: ["*"]

ddd:
  jwt: #token校验
    enabled: false
    checkTokenEndpointUrl: http://192.168.5.61:7099/api/v1/pub/verify
    oldVerifySupport: false
    checkOldTokenEndpointUrl: http://192.168.1.7:30280/WebVerify
    includes: #接口列表
    - /api/v?/**
    excludes:
    - /api/v?/**
  signature: #接口签名校验
    enabled: false
    includes:
    - /api/*
  security: #session校验
    enabled: false

#自定义配置
applicationconfig:
  #  userServiceUrl: http://192.168.5.29:7081 #用户服务,开发
  userServiceUrl: http://192.168.5.61:7081 #用户服务,测试
  bookServiceUrl: http://192.168.5.59:7090 #书架服务
  packageServiceUrl: http://192.168.5.59:7088 #书本打包服务
  questionServiceUrl: http://192.168.5.59:7087 #习题库服务