#单元测试多环境连接配置[dev：开发环境；test：测试环境；prod：生产环境]
spring:
  profiles:
    active: dev

swagger.enabled: true

server:
  port: 9300

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: DEBUG
    com.xuehai.application.BookServerClient: DEBUG
    com.xuehai.application.UserServiceClient: DEBUG
    com.xuehai.application.PackageServiceClient: DEBUG
    com.xuehai.application.QuestionServiceClient: DEBUG